### ISSUE TITLE
getLogManager(config.elogger) sets the wrong level for a named transport

### ISSUE THREAD

**Issue by sshanson** [jpravetz/epdoc-logger#2]
Given a config file:

{ sid: true,
  static: false,
  errorStack: true,
  level: 'debug',
  transports: [ 'loggly' ],
  file:
   { timestamp: 'iso',
     path: '{ROOT}/log/{DATE:YYYYMMDD_HHmmSS}_publisher.log' },
  console: { timestamp: 'iso', level: 'info' },
  loggly:
   { level: 'info',
     subdomain: 'plutotv',
     token: '2f546e8a-d479-428c-8a3d-1f3660db8bcf' } }

the logger sets the loggly level to elogger.level (== 'debug') instead of elogger.loggly.level (== 'info').

**Comment by jpravetz** [comment]
Yes it does. It's a bit confusing, but I hadn't yet arrived at an unconfusing answer. You should just have to make sure you set the config correctly. Is this a big problem?

**Comment by sshanson** [comment]
My bug - I was setting a second loggly transport with different log levels.

The (second) confusing part though is the role of config.epdoc.level. We thought it set a default level for transports that don't have their own level set. That's not how it is used though. The config.epdoc.level is really a first-level gateway. ie the message has to have at least the level of config.epdoc.level for the message to get sent on to the transports, who then compare the message's level to the transport level.

If it's set as 
config :
{
epdoc: {
   level : 'warn',
   console : {
       level : 'info'
   }
}
}
a message with level 'info' is not written to the console even though the console.level is set to 'info' because 'info' < epdoc.level (== 'warn').
